CREATE PROC FI_SP_IncBeneficiarioV2
    @IDCLIENTE     BIGINT       ,
	@NOME          VARCHAR (50) ,
	@CPF		   VARCHAR (15)
AS
BEGIN
	INSERT INTO BENEFICIARIOS (IDCLIENTE,NOME, CPF) 
	VALUES (@IDCLIENTE,@NOME,@CPF)

	SELECT SCOPE_IDENTITY()
END